networks:
  forgejo:
    external: false

volumes:
  # forgejo_pg:
  forgejo_data:

services:
  server:
    image: codeberg.org/forgejo/forgejo:9.0.2
    container_name: forgejo
    env_file:
      - /home/lorenzo/configs/.env
    restart: always
    networks:
      - forgejo
    volumes:
      - forgejo_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '3000:3000'
      - '222:22'
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    user: '0:0'
    env_file:
      - /home/lorenzo/configs/.db_env
    networks:
      - forgejo
    volumes:
      - /users/lorenzo/home/forgejo_pg:/var/lib/postgresql/data
