---
- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: ./project/
    dest: /home/lorenzo/configs/nbarr/
    owner: lorenzo
    mode: '0644'
  become: true

- name: Start nbarr container
  community.docker.docker_compose:
    project_name: nbarr
    build: true
    definition:
      version: '3.8'
      services:
        nbarr:
          container_name: nbarr
          build:
            context: /home/lorenzo/configs/nbarr/
            dockerfile: Dockerfile
          ports:
            # Web UI
            - '80:5000'
            # Stream
            - '3000:5946'
  register: output

- ansible.builtin.debug:
    var: output

- ansible.builtin.assert:
    that:
      - "output.services.nbarr.nbarr.state.running"