services:
  glance:
    image: glanceapp/glance
    volumes:
      # - /home/lorenzo/configs/glance.yml:/app/glance.yml
      - ./configs/glance.yml:/app/glance.yml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080
    restart: unless-stopped
