version: '3.8'
volumes:
  unifi-data:

services:
  unifi_controller:
    image: lscr.io/linuxserver/unifi-controller:8.0.7
    container_name: unifi_controller
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - unifi-data:/config

    ports:
      # Unifi web admin port
      - 8443:8443
      # Unifi STUN port
      - 3478:3478/udp
      # Required for AP discovery
      - 10001:10001/udp
      # Required for device communication
      - 8080:8080
      # Required for Make controller discoverable on L2 network option
      - 1900:1900/udp
      - 6789:6789
    restart: unless-stopped
