---
- name: Start nginx-proxy-manager container
  community.docker.docker_compose:
    project_name: npm
    build: true
    definition:
      version: "3.8"
      networks:
        vpn:
          external: true

      volumes:
        nginx-proxy-manager-data:
        nginx-proxy-manager-le:

      services:
        app:
          image: 'jc21/nginx-proxy-manager:2.12.1'
          container_name: npm
          restart: unless-stopped
          ports:
            - '443:443'
            - '80:80'
            # Admin dashboard. We reverse proxy to the dashboard, but in case
            # it stops working, we can still access it directly.
            - '81:81'
          volumes:
            - nginx-proxy-manager-data:/data
            - nginx-proxy-manager-le:/etc/letsencrypt
          dns:
            - 172.40.0.11
          networks:
            vpn:
            # Need to do this otherwise it can't communicate
            # with pihole properly and can't proxy to its own
            # container + it can't access the dns server
            # It effectively leaves it out of the vpn network
              ipv4_address: 172.40.0.10

  register: output

- ansible.builtin.debug:
    var: output

- ansible.builtin.assert:
    that:
      - "output.services.app.npm.state.running"
