---
- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: ./project/
    dest: /home/lorenzo/configs/location-tracker/
    owner: lorenzo
    mode: '0644'
  become: true

- name: Copy compose file with owner and permissions
  ansible.builtin.copy:
    src: ./docker-compose.yml
    dest: /home/lorenzo/configs/docker-compose.yml
    owner: lorenzo
    mode: '0644'
  become: true

- name: Start location-tracker container
  community.docker.docker_compose_v2:
    project_name: location-tracker 
    build: always
    project_src: '/home/lorenzo/configs'
  register: output

- ansible.builtin.debug:
    var: output

# This assertion isn't working
- ansible.builtin.assert:
    that:
      - "output.services.location-tracker.location-tracker.state.running"