version: '3.8'
volumes:
  location_data:
services:
  location-tracker:
    container_name: location-tracker
    build:
      context: /home/lorenzo/configs/location-tracker/
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - location_data:/app/data
