version: "3.8"
networks:
  vpn:
    external: true

volumes:
  n8n:

services:
  n8n:
    # We build from a local dockerfile because we add a couple things to the image
    build: .
    restart: unless-stopped
    container_name: n8n
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      # n8n creates the webhook URL by combining N8N_PROTOCOL, N8N_HOST and N8N_PORT. If n8n runs behind a reverse proxy, that won't work. 
      # That's because n8n runs internally on port 5678 but is exposed to the web using the reverse proxy on port 443. 
      # In that case, it's important to set the webhook URL manually so that n8n can display it correctly in the Editor UI and register the 
      # correct webhook URLs with external services.
      - WEBHOOK_URL=https://auto.picco.li/
    volumes:
      - n8n:/home/node/.n8n
      - /home/lorenzo/repos/lobsidian:/files/lobsidian
      - /home/lorenzo/.ssh/id_ed25519-github:/home/node/.ssh/id_ed25519
      - /home/lorenzo/.ssh/known_hosts:/home/node/.ssh/known_hosts
    networks:
      - vpn
    labels:
      # Watchtower doesn't like that we use `build: .` with our own custom Dockerfile. So we need to disable it for this container
      # https://github.com/containrrr/watchtower/issues/1455
      - com.centurylinklabs.watchtower.enable=false