networks:
  socket_proxy:
    name: socket_proxy

services:
  dozzle:
    image: amir20/dozzle:v8.9.0
    environment:
      DOCKER_HOST: tcp://socketproxy:2375
      DOZZLE_REMOTE_AGENT: '192.168.40.28:7007,192.168.40.23:7007,192.168.40.18:7007,192.168.40.19:7007,192.168.40.27:7007,192.168.40.16:7007,192.168.40.7:7007,192.168.40.14:7007,192.168.20.5:7007,192.168.20.3:7007'
      DOZZLE_ENABLE_ACTIONS: true
    networks:
      - socket_proxy
    depends_on:
      - socketproxy
    ports:
      - 8080:8080
  socketproxy:
    image: tecnativa/docker-socket-proxy:0.3.0
    privileged: true
    environment:
      CONTAINERS: 1
      ALLOW_START: 1
      ALLOW_RESTARTS: 1
      ALLOW_STOP: 1
      INFO: 1
      CONFIGS: 1
      IMAGES: 1
      NETWORKS: 1
      SYSTEM: 1
      POST: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket_proxy
