---
- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: ./configs/
    dest: /home/lorenzo/configs/traefik/
    owner: lorenzo
    mode: '0644'
  become: true

- name: Start traefik container
  community.docker.docker_compose:
    project_name: traefik
    build: true
    definition:
      version: '3.8'

      networks:
        web:
          external: true

      volumes:
        traefik:

      services:
        traefik:
          image: traefik:2.10.5
          restart: unless-stopped
          command:
            - '--log.level=DEBUG'
          container_name: traefik
          ports:
            - '443:443'
            - '80:80'
          environment:
            NAMECHEAP_API_USER: "{{ TRAEFIK_NAMECHEAP_API_USER }}" 
            NAMECHEAP_API_KEY: "{{ TRAEFIK_NAMECHEAP_API_KEY }}"
          networks:
            web:
              ipv4_address: 172.20.0.10
              aliases:
                - spotify.udjaiahs.li
                - api.spotify.udjaiahs.li
          volumes:
            - traefik:/acme
            - '/home/lorenzo/configs/traefik/traefik.toml:/traefik.toml'
            - '/home/lorenzo/configs/traefik/traefik_dynamic.toml:/traefik_dynamic.toml'
            # So that Traefik can listen to the Docker events
            - /var/run/docker.sock:/var/run/docker.sock
  register: output

- ansible.builtin.debug:
    var: output

- ansible.builtin.assert:
    that:
      - "output.services.traefik.traefik.state.running"

