---
- name: Ensure configs dir exists
  file:
    path: /home/lorenzo/configs/traefik
    state: directory

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: ./configs/
    dest: /home/lorenzo/configs/traefik/
    owner: lorenzo
    mode: '0644'
  become: true

- name: Copy env var for docker compose
  copy:
    dest: /home/lorenzo/configs/traefik/.env
    content: |
      NAMECHEAP_API_USER="{{ TRAEFIK_NAMECHEAP_API_USER }}" 
      NAMECHEAP_API_KEY="{{ TRAEFIK_NAMECHEAP_API_KEY }}"
    mode: '0600'


- name: Start traefik container
  community.docker.docker_compose_v2:
    project_name: traefik
    build: always
    project_src: '/home/lorenzo/configs/traefik'
  register: output

- ansible.builtin.debug:
    var: output