# ====== General ======
- name: Ensure Pip is installed.
  package:
    name:  python3-pip
    state: present

# This is being deprecated. Now docker-compose is docker compose. I believe it's already installed
# with the docker.yml file. The only change is that  community.docker.docker_compose should
# become community.docker.docker_compose_v2.
# I'm keeping this here for the time being until I understand how it impacts my active machines
- name: Install Docker Compose using Pip.
  pip:
    name: docker-compose
    state: present
    executable: pip3

- name: Ensure Docker is started.
  service:
    name: docker
    state: started
    enabled: true
