---
- name: Ensure rsync installed
  apt:
    name: rsync 
    state: present
    update_cache: true
  become: true

- name: Ensure acl installed
  apt:
    name: acl 
    state: present
    update_cache: true
  become: true

- name: Give access to docker volumes
  ansible.builtin.shell: sudo setfacl -R -m u:lorenzo:rX /var/lib/docker
  become: true
