pageInfo:
  title: Lorenzo's dashboard
  description: ''
appConfig:
  theme: one-dark
  layout: auto
  iconSize: large
  language: en
  faviconApi: google
sections:
  - name: Self hosted cloud
    items:
      - title: Grafana
        description: 'Server monitoring'
        icon: grafana.png
        url: https://grafana.picco.li/
        target: newtab
        statusCheck: false
        statusCheckInterval: 300
      - title: Portainer
        description: 'Container management'
        icon: portainer.svg
        url: https://portainer.picco.li/
        target: newtab
        statusCheck: false
        statusCheckInterval: 300
      - title: Traefik
        description: 'Reverse proxy'
        icon: traefik-logo.png
        url: https://rp.picco.li/
        statusCheckUrl: http://rp.picco.li
        target: newtab
        statusCheckAcceptCodes: 401
        statusCheck: false
        statusCheckInterval: 300
      - title: Wireguard
        description: 'Fast and modern VPN'
        icon: wireguard.png
        url: https://wg.picco.li/
        statusCheckUrl: http://wg.picco.li
        target: newtab
        statusCheckAcceptCodes: 401
        statusCheck: false
        statusCheckInterval: 300
      - title: Pi-hole
        description: 'Network-wide Ad Blocking ﻿'
        icon: pihole.png
        url: https://dns.picco.li/admin/
        statusCheckUrl: http://dns.picco.li/admin/
        target: newtab
        statusCheck: false
        statusCheckInterval: 300
      - title: Expenses app
        description: 'Manage and explore expenses'
        icon: si-cashapp
        url: https://expenses.picco.li/
        statusCheckUrl: https://expenses.picco.li/
        target: newtab
        statusCheck: false
        statusCheckInterval: 300
      - title: What's up docker?
        description: 'Manage docker images updates'
        icon: si-docker
        url: https://wud.picco.li/
        statusCheckUrl: https://wud.picco.li/
        target: newtab
        statusCheck: false
        statusCheckInterval: 300
      - title: Syncthing
        description: 'Keeps folders in sync'
        icon: syncthing.png
        url: https://sync.picco.li/
        statusCheckUrl: https://sync.picco.li/
        target: newtab
        statusCheck: false
        statusCheckInterval: 300
      - title: N8N
        description: 'All kinds of automation'
        icon: n8n.png
        url: https://auto.picco.li/
        statusCheckUrl: https://auto.picco.li/
        target: newtab
        statusCheck: false
        statusCheckInterval: 300
    
    displayData:
      sortBy: most-used
      cols: 2
  - name: Udjaiahs TV
    items:
      - title: Ultra
        description: 'Seedbox'
        icon: ultra.png
        url: https://cp.ultraseedbox.com/#/userservice/159b50d9-921e-43f4-aaaa-d022920b42c1
        target: newtab
        statusCheck: false
        statusCheckInterval: 300
      - title: Ombi
        description: 'Media request'
        icon: ombi.png
        url: https://diogocarmo.ghost.usbx.me/ombi/
        target: newtab
        statusCheck: false
        statusCheckInterval: 300
      - title: Transmission
        description: 'Torrent Client'
        icon: transmission.png
        url: https://diogocarmo.ghost.usbx.me/transmission/web/
        statusCheckAcceptCodes: 401
        target: newtab
        statusCheck: false
        statusCheckInterval: 300
      - title: Sonarr
        description: 'TV Show Manager'
        icon: sonarr.png
        url: https://diogocarmo.ghost.usbx.me/sonarr/
        target: newtab
        statusCheck: false
        statusCheckInterval: 300
      - title: File browser
        description: 'File manager'
        icon: si-files
        url: https://diogocarmo.ghost.usbx.me/filebrowser
        target: newtab
        statusCheck: false
        statusCheckInterval: 300
    displayData:
      sortBy: most-used
  - name: Quick access
    items:
      - title: ChatGPT
        description: Chat bot developed by OpenAI
        icon: chatGPT.svg
        url: https://chat.openai.com/chat
      - title: Private mail
        description: 'My private email provider'
        icon: si-gmail
        url: https://privateemail.com/
        target: newtab
        statusCheck: false
        statusCheckInterval: 300
    displayData:
      sortBy: most-used
      cols: 1
