version: "2"
networks:
  web:
    external: true
services:
  node:
    image: "node:14"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    command: "npm start"
    # extra_hosts:
    #   - "expenses.picco.li:172.20.0.10"
    # network_mode: web
    networks:
      - web
        # ipv4_address: 172.20.0.10