---
- name: Create lobsidian repo directory
  file:
    path: "/home/lorenzo/lobsidian"
    state: directory
  become_user: lorenzo
  become: true

- name: Ensure git installed
  apt:
    name: git
    state: present
    update_cache: true
  become: true

- name: Checkout lobsidian git repo
  git:
    repo: "https://{{ PRIVATE_GIT_USER | urlencode }}:{{ PRIVATE_GIT_PASS | urlencode }}@git.picco.li/lorenzopicoli/lobsidian.git"
    dest: "/home/lorenzo/lobsidian"
    accept_hostkey: true
  become_user: lorenzo
  become: true

- name: Make update git global email
  community.general.git_config:
    name: user.email
    scope: global
    value: 'lorenzo@picco.li'
  become_user: lorenzo
  become: true

- name: Make update git global name
  community.general.git_config:
    name: user.name
    scope: global
    value: 'Automatic cron'
  become_user: lorenzo
  become: true
