version: '3.8'

networks:
  web:
    external: true
  # internal:
  #   external: false

volumes:
  spotify-data:

services:
  server:
    image: yooooomi/your_spotify_server:nightly
    restart: unless-stopped
    networks:
      - web
    env_file:
      - /home/lorenzo/configs/spotify/.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-spotify.rule=Host(`api.spotify.udjaiahs.com`)
      - traefik.http.routers.api-spotify.tls.certresolver=lets-encrypt
      - traefik.http.routers.api-spotify.service=api-spotify
      - traefik.http.services.api-spotify.loadbalancer.server.port=8080
    dns:
      - 192.168.40.7
  web:
    image: yooooomi/your_spotify_client:nightly
    restart: unless-stopped
    networks:
      - web
    env_file:
      - /home/lorenzo/configs/spotify/.web_env
    labels:
      - traefik.enable=true
      - traefik.http.routers.spotify.rule=Host(`spotify.udjaiahs.com`)
      - traefik.http.routers.spotify.tls.certresolver=lets-encrypt
      - traefik.http.routers.spotify.service=spotify
      - traefik.http.services.spotify.loadbalancer.server.port=3000
