- name: Fix backup for all services
  hosts: all
  strategy: free
  become: true
  vars:
    username: lorenzo
    device_type: normal
  tasks:
    - name: Setup for Active Backup
      ansible.builtin.include_tasks: tasks/setup-rsync-backup.yml

