- name: Setup Obsidian
  hosts:
    - obsidian
  become: true

  vars:
    username: lorenzo
    device_type: normal
  vars_files:
    - env_vars.yml

  tasks:
    - name: Update server and install essential packages
      ansible.builtin.include_tasks: tasks/ssh.yml

    - name: Setup linux firewall
      ansible.builtin.include_tasks: tasks/firewall.yml
    
    - name: Setup syncthing firewall
      ansible.builtin.include_tasks: tasks/services/internal/syncthing/syncthing-firewall.yml

    - name: Install docker
      ansible.builtin.include_tasks: tasks/docker.yml
    
    - name: Install docker compose
      ansible.builtin.include_tasks: tasks/install-compose.yml
    
    - name: Deploy syncthing docker apps
      ansible.builtin.include_tasks: "tasks/services/internal/{{ item }}/compose-task.yml"
      loop:
        - syncthing
        - dozzle-agent
    
    - name: Setup for Active Backup
      ansible.builtin.include_tasks: tasks/setup-rsync-backup.yml