- name: Setup raspberrypi
  hosts:
    - raspberrypi
  become: true
  vars:
    username: lorenzo
    device_type: pi
  vars_files:
    - env_vars.yml

  tasks:
    - name: Update server and install essential packages
      ansible.builtin.include_tasks: tasks/ssh.yml

    - name: Setup linux firewall
      ansible.builtin.include_tasks: tasks/firewall.yml

    - name: Install docker
      ansible.builtin.include_tasks: tasks/docker-arm.yml
    
    - name: Add docker web network
      ansible.builtin.include_tasks: tasks/docker-web-network.yml
    

    - name: Deploy raspberry docker apps
      ansible.builtin.include_tasks: "tasks/services/external/{{ item }}/compose-task.yml"
      loop:
        - traefik
        - spotify

    - name: Deploy radioactive internal docker apps
      ansible.builtin.include_tasks: "tasks/services/internal/{{ item }}/compose-task.yml"
      loop:
        - dozzle-agent
    
    - name: Setup for Traefik
      ansible.builtin.include_tasks: tasks/traefik-acme-perm.yml
