- name: Setup raspberrypi
  hosts:
    - raspberrypi
  become: true
  vars:
    username: lorenzo
    device_type: pi
  vars_files:
    - env_vars.yml

  tasks:
    - name: Update server and install essential packages
      ansible.builtin.include_tasks: tasks/ssh.yml

    - name: Setup linux firewall
      ansible.builtin.include_tasks: tasks/firewall.yml

    - name: Install docker
      ansible.builtin.include_tasks: tasks/docker-arm.yml
    
    - name: Install docker compose
      ansible.builtin.include_tasks: tasks/install-compose.yml
      
    - name: Set docker firewalls
      ansible.builtin.include_tasks: tasks/docker-firewall.yml
    
    - name: Deploy raspberry docker apps
      ansible.builtin.include_tasks: "tasks/services/external/{{ item }}/compose-task.yml"
      loop:
        - traefik
        - spotify

    - name: Setup for Active Backup
      ansible.builtin.include_tasks: tasks/setup-rsync-backup.yml
    
    - name: Setup for Traefik
      ansible.builtin.include_tasks: tasks/traefik-acme-perm.yml
