---
- name: Ensure configs dir exists
  file:
    path: /home/lorenzo/configs
    state: directory
    
- name: Ensure configs dir exists
  file:
    path: /home/lorenzo/configs/mgob
    state: directory

- name: Copy compose file with owner and permissions
  ansible.builtin.copy:
    src: ./docker-compose.yml
    dest: /home/lorenzo/configs/docker-compose.yml
    owner: lorenzo
    mode: '0644'
  become: true
  
- name: Copy mgob config file with owner and permissions
  ansible.builtin.copy:
    src: ./configs/mgob_config.yml
    dest: /home/lorenzo/configs/mgob/mgob_config.yml
    owner: lorenzo
    mode: '0644'
  become: true

- name: Copy env var for docker compose
  copy:
    dest: /home/lorenzo/configs/.env
    content: |

    mode: '0600'

- name: Start spotify mongo container
  community.docker.docker_compose_v2:
    project_name: your_spotify_db
    build: always
    project_src: '/home/lorenzo/configs'
  register: output

- ansible.builtin.debug:
    var: output