---
- name: Start spotify database container
  community.docker.docker_compose:
    project_name: your_spotify_db
    build: true
    definition:
      version: "3.8"

      volumes:
        spotify-data:

      services:
        mongo:
          container_name: mongo
          image: mongo:6.0.5
          ports:
            - '27017:27017'

          volumes:
            - /users/lorenzo/home/mongodb:/data/db
          user: "0:0"
  register: output

- ansible.builtin.debug:
    var: output

- ansible.builtin.assert:
    that:
      - "output.services.mongo.mongo.state.running"

