version: '3.8'

# networks
# create a network 'guacnetwork_compose' in mode 'bridged'
networks:
  vpn:
    external: true
  internal:
    external: false
volumes:
  guacd_drive:
  guacd_record:
  guac_psql_data:


services:
  guacd:
    image: guacamole/guacd
    container_name: guacd
    restart: unless-stopped
    networks:
      internal:
    volumes:
      - guacd_drive:/drive:rw
      - guacd_record:/record:rw
  postgres:
    image: postgres:13.4-buster
    container_name: postgres_guacamole
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
    networks:
      internal:
    volumes:
      - ./init:/docker-entrypoint-initdb.d:z
      - guac_psql_data:/var/lib/postgresql/data:Z
    env_file:
      - .env

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    restart: unless-stopped
    depends_on:
      - guacd
      - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_USER: guacamole_user
    links:
      - guacd
    # volumes:
    #   - ./guacamole.properties:/home/guacamole/.guacamole/guacamole.properties
    networks:
      internal:
      vpn:
    env_file:
      - .env
    # ports:
# enable next line if not using nginx
#    - 8080:8080/tcp # Guacamole is on :8080/guacamole, not /.
# enable next line when using nginx
    # - 8080/tcp