---
- name: Ensure configs dir exists
  file:
    path: /home/lorenzo/configs
    state: directory

- name: Copy compose file with owner and permissions
  ansible.builtin.copy:
    src: ./docker-compose.yml
    dest: /home/lorenzo/configs/docker-compose.yml
    owner: lorenzo
    mode: '0644'
  become: true

- name: Copy env var for docker compose
  copy:
    dest: /home/lorenzo/configs/.env
    content: |
       COUCHDB_USER="{{ HARES_DB_USERNAME }}"
       COUCHDB_PASSWORD="{{ HARES_DB_PASSWORD }}"

    mode: '0600'

- name: Ensure local.d dir exists
  file:
    path: /home/lorenzo/configs/local.d
    state: directory

- name: Copy couchdb config
  copy:
    src: ./local.ini
    dest: /home/lorenzo/configs/local.d/local.ini

    mode: '0600'

- name: Start hares container
  community.docker.docker_compose_v2:
    project_name: hares
    build: always
    project_src: '/home/lorenzo/configs'
  register: output

- ansible.builtin.debug:
    var: output

- name: Prune images
  community.docker.docker_prune:
    containers: false
    images: true
    networks: false
    volumes: false
    builder_cache: false

# This assertion isn't working
# - ansible.builtin.assert:
#     that:
#       - "output.services.location-tracker.location-tracker.state.running"
